/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:ad227c60-b3ee-4604-aabd-46a0bdbe8b25",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_IN79wu7u3",
    "aws_user_pools_web_client_id": "7os1v535tvj00l6p4qdml09sqq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "myappff541ed9f594491087c07698d92d10e3180905-dev",
    "aws_user_files_s3_bucket_region": "sa-east-1",
    "aws_appsync_graphqlEndpoint": "https://sy3jxfinvfb3jesv7pa5hsdzvq.appsync-api.sa-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "sa-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-56zy2fdrbnem7lztb6yggvgs2u"
};


export default awsmobile;
